# Generated by rust2rpm 27
%bcond check 1

# prevent library files from being installed
%global cargo_install_lib 0

Name:           mirafetch
Version:        0.1.0
Release:        %autorelease
Summary:        Rust reimplementation of Hyfetch wih a focus on speed

SourceLicense:  EUPL-1.2
License:        EUPL-1.2
# LICENSE.dependencies contains a full license breakdown

URL:            https://github.com/ArgentumCation/mirafetch
Source:         https://github.com/ArgentumCation/mirafetch
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          mirafetch-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 26

%global _description %{expand:
A Rust reimplementation of Hyfetch wih a focus on speed.}

%description %{_description}

%prep
%autosetup -n mirafetch-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE.md
%license LICENSE.dependencies
%doc README.md
%{_bindir}/mirafetch

%changelog
%autochangelog
