name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    # See https://github.com/ArgentumCation/mirafetch/pull/15#issuecomment-1826278518
    # - name: Run tests
    #   run: cargo test --verbose
